version: '2'

services:
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html/public
      - ./app/static:/var/www/html/app/static/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx
    links:
      - phalcon
      - mongo-express
      - mongo


  mongo:
    build: ./db
    restart: always
    ports:
            - "27017:27017"
    
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123456
      MONGO_INITDB_DATABASE: incubator
    volumes:
      - ./dbbase:/data/db


         
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_AUTH_USERNAME: root
      ME_CONFIG_MONGODB_AUTH_PASSWORD: 123456

    
    links:
      - mongo

  phalcon:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    restart: always
    ports:
    - "9000:9000"
    volumes:
    - ./:/var/www/html/
    - ./public:/var/www/html/public
    - ./vendor:/var/www/html/vendor
    - ./composer.json:/var/www/html/composer.json

  redis:
      image: redis:alpine
      restart: always
      ports:
            - "6379:6379"
      links:
            - phalcon
            
  aerospike:
        image: aerospike
        ports:
            - "3000:3000"

    
  beanstalk:
        image: schickling/beanstalkd
        ports:
            - "11300:11300"
  memcached:
        image: memcached
        ports:
            - "11211:11211"

   





